AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
    aws-sap-cert-auth
    SAM Template for SAP Cert based auth using Lambda
Globals:
    Function:
        Timeout: 29
Parameters:
    Environment:
        Description: Unique name to add all the resources that are created through this template 
        Type: String
    ServerKeyParameterStore:
        Description: Name of the parameter store where SAP Server Key is stored
        Type: String
    UserKeyParameterStore:
        Description: Name of the parameter store where User Server Key is stored
        Type: String
    S3BucketForKeys:
        Description: Name of the S3 bucket where the certificates and keys will be stored
        Type: String
    ServerCertFile:
        Description: Name of the Server Certificate file 
        Type: String
    ServerKeyFile:
        Description: Name of the Server Key file 
        Type: String

Metadata:
  AWS::ServerlessRepo::Application:
    Name: aws-sap-cert-auth
    Description: Lambda function for single signon to SAP using user certificates
    Author: KK Ramamoorthy
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE.txt
    ReadmeUrl: sam-repo/README.md
    Labels: ['saponaws','sap','lambdaauth','certificateauth']
    HomePageUrl: https://code.amazon.com/packages/Aws-sap-cert-auth/trees/master
    SemanticVersion: 0.0.1
    SourceCodeUrl: https://code.amazon.com/packages/Aws-sap-cert-auth/trees/master

Resources:
    SAPUserCertGeneratorLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: !Sub ${Environment}-aws-sap-user-cert-generator
            Description: Lamda Layer to generate user certificate for SAP
            ContentUri: layers/aws-sap-user-cert-generator/
            CompatibleRuntimes:
                - nodejs8.10
            LicenseInfo: 'Available under the MIT-0 license.'
            RetentionPolicy: Retain

    SAPUserCertAuthTestFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: !Sub ${Environment}-aws-sap-user-cert-auth-test
            CodeUri: aws-sap-user-cert-auth-test/
            Handler: app.lambdaHandler
            Runtime: nodejs8.10
            Policies:
                - S3CrudPolicy:
                    BucketName: !Ref S3BucketForKeys
                - SSMParameterReadPolicy:
                    ParameterName: !Ref ServerKeyParameterStore
                - SSMParameterReadPolicy:
                    ParameterName: !Ref UserKeyParameterStore    
            Environment:
                Variables:
                    S3_BUCKET_FOR_CERTS:    !Ref S3BucketForKeys
                    CERT_EXPIRY_IN_DAYS:    30
                    SERVER_CERT_FILE_NAME:  !Ref ServerCertFile
                    SERVER_KEY_FILE_NAME:   !Ref ServerKeyFile
                    SERVER_KEY_PASS_PARAM:  !Ref ServerKeyParameterStore
                    USER_KEY_PASS_PARAM:    !Ref UserKeyParameterStore
                    WRITE_CONSOLE_LOG:      "false"
                    FORCE_CREATE_NEW_USER_CERT: "false"
                    REJECT_SELF_SIGNED_CERTS: "true"
                    SAP_HOST_URL: "<<YOUR SAP HOST URL. For e.g. mysaphttpurl.com without https:// >>"
                    SAP_HOST_PORT: "<<YOUR SAP HTTPs port. For e.g. 44300>>"
            Layers:
                - !Ref SAPUserCertGeneratorLayer

Outputs:
    SAPUserCertAuthTestFunction:
        Description: "SAP user cert auth test function ARN"
        Value: !GetAtt SAPUserCertAuthTestFunction.Arn
